import { defineStore } from 'pinia'

export const useProdutosStore = defineStore('produtos', () => {

  const produtos = [
    {
      nome: 'Painel Solar 590W Monocristalino Half-Cell',
      imageUrl: 'placa',
      preco: 790.0,
      material: ['Silício Monocristalino'],
      potencia: 590,
      marca: 'elgin',
      parcelas: 'em até 10x de R$ 100,00',
      qntdVendas: 1,
      VerMais: {
        'descricao': 'Caixa de Conexão IP 68 com 3 diodos de by-pass',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Moldura': 'Alumínio Anodizado',
        'Coeficiente de Temperatura (Pmax)': '0.35 %/°C',
        'Coeficiente de Temperatura (Voc)': '0.27 %/°C',
        'Temperatura de Operação da Placa': '- 40 ~ + 85 °C',
        'Temperatura de Operação Ambiente': '45°C (± 2°C)',
        'Tipo de Vidro Frontal': '3.2mm temperado',
        'Nº de Células': '144 (6x24)',
        'Coeficiente de Temperatura (Isc)': '0.050 %/°C',
        'Dimensões (AxLxP)': '2279 X 1134 X 35mm',
        'Máxima carga estática na parte frontal (ex:carga sob placa)': '5400Pa',
        'Tipo de Material': 'Monocristalino (Half-cell)',
        'Tipo de Conector': 'Conectores MC4',
        'Eficiência do Módulo': '21.30%',
        'Nível de Eficiência Energética no Inmetro': 'Nível A',
        'Máxima carga estática traseira (ex:vento)': '2400Pa',
        'Área da seção do': 'cabo:4mm²',
        'REGISTRO INMETRO': '007202/2021',
        'Corrente Máxima por Fusíveis em Série': '25A',
        'Peso': '29kg',
        'CARACTERÍSTICAS': 'Economia Imediata Certificado pelo INMETRO Resistente'
      },
      id: 0,
      categoria:"kits-solares"
    },
    {
      nome: 'Cabo Solar 4mm 30M Preto',
      imageUrl: 'caboSolar',
      preco: 1000.0,
      parcelas: 'em até 10x de R$ 100,00',
      material: ['Células de Silício Amorfo'],
      potencia: 400,
      marca: 'weg',
      qntdVendas: 3,
      VerMais: {
        'descricao': 'Caixa de Conexão IP 68 com 3 diodos de by-pass',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Moldura': 'Alumínio Anodizado',
        'Coeficiente de Temperatura (Pmax)': '0.35 %/°C',
        'Coeficiente de Temperatura (Voc)': '0.27 %/°C',
        'Temperatura de Operação da Placa': '- 40 ~ + 85 °C',
        'Temperatura de Operação Ambiente': '45°C (± 2°C)',
        'Tipo de Vidro Frontal': '3.2mm temperado',
        'Nº de Células': '144 (6x24)',
        'Coeficiente de Temperatura (Isc)': '0.050 %/°C',
        'Dimensões (AxLxP)': '2279 X 1134 X 35mm',
        'Máxima carga estática na parte frontal (ex:carga sob placa)': '5400Pa',
        'Tipo de Material': 'Monocristalino (Half-cell)',
        'Tipo de Conector': 'Conectores MC4',
        'Eficiência do Módulo': '21.30%',
        'Nível de Eficiência Energética no Inmetro': 'Nível A',
        'Máxima carga estática traseira (ex:vento)': '2400Pa',
        'Área da seção do': 'cabo:4mm²',
        'REGISTRO INMETRO': '007202/2021',
        'Corrente Máxima por Fusíveis em Série': '25A',
        'Peso': '29kg',
        'CARACTERÍSTICAS': 'Economia Imediata Certificado pelo INMETRO Resistente'
      },
      id: 2,
      categoria:"cabos"
    },
    {
      nome: 'Kit Energia Solar 1,14kWp 570W',
      imageUrl: 'estruturaSolar',
      preco: 2000.0,
      parcelas: 'em até 10x de R$ 100,00',
      material: ['alumínio'],
      potencia: 500,
      marca: 'weg',
      qntdVendas: 2,
      VerMais: {
        'descricao': 'Caixa de Conexão IP 68 com 3 diodos de by-pass',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Moldura': 'Alumínio Anodizado',
        'Coeficiente de Temperatura (Pmax)': '0.35 %/°C',
        'Coeficiente de Temperatura (Voc)': '0.27 %/°C',
        'Temperatura de Operação da Placa': '- 40 ~ + 85 °C',
        'Temperatura de Operação Ambiente': '45°C (± 2°C)',
        'Tipo de Vidro Frontal': '3.2mm temperado',
        'Nº de Células': '144 (6x24)',
        'Coeficiente de Temperatura (Isc)': '0.050 %/°C',
        'Dimensões (AxLxP)': '2279 X 1134 X 35mm',
        'Máxima carga estática na parte frontal (ex:carga sob placa)': '5400Pa',
        'Tipo de Material': 'Monocristalino (Half-cell)',
        'Tipo de Conector': 'Conectores MC4',
        'Eficiência do Módulo': '21.30%',
        'Nível de Eficiência Energética no Inmetro': 'Nível A',
        'Máxima carga estática traseira (ex:vento)': '2400Pa',
        'Área da seção do': 'cabo:4mm²',
        'REGISTRO INMETRO': '007202/2021',
        'Corrente Máxima por Fusíveis em Série': '25A',
        'Peso': '29kg',
        'CARACTERÍSTICAS': 'Economia Imediata Certificado pelo INMETRO Resistente'
      },
      id: 4,
      categoria:"inversores",
      promocao:true
    },
    {
      nome: 'Kit Energia Solar 1,14kWp 570W',
      imageUrl: 'placa3',
      preco: 2000.0,
      parcelas: 'em até 10x de R$ 100,00',
      material: ['alumínio'],
      potencia: 400,
      marca: 'elgin',
      qntdVendas: 1,
      VerMais: {
        'descricao': 'Caixa de Conexão IP 68 com 3 diodos de by-pass',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Moldura': 'Alumínio Anodizado',
        'Coeficiente de Temperatura (Pmax)': '0.35 %/°C',
        'Coeficiente de Temperatura (Voc)': '0.27 %/°C',
        'Temperatura de Operação da Placa': '- 40 ~ + 85 °C',
        'Temperatura de Operação Ambiente': '45°C (± 2°C)',
        'Tipo de Vidro Frontal': '3.2mm temperado',
        'Nº de Células': '144 (6x24)',
        'Coeficiente de Temperatura (Isc)': '0.050 %/°C',
        'Dimensões (AxLxP)': '2279 X 1134 X 35mm',
        'Máxima carga estática na parte frontal (ex:carga sob placa)': '5400Pa',
        'Tipo de Material': 'Monocristalino (Half-cell)',
        'Tipo de Conector': 'Conectores MC4',
        'Eficiência do Módulo': '21.30%',
        'Nível de Eficiência Energética no Inmetro': 'Nível A',
        'Máxima carga estática traseira (ex:vento)': '2400Pa',
        'Área da seção do': 'cabo:4mm²',
        'REGISTRO INMETRO': '007202/2021',
        'Corrente Máxima por Fusíveis em Série': '25A',
        'Peso': '29kg',
        'CARACTERÍSTICAS': 'Economia Imediata Certificado pelo INMETRO Resistente'
      },
      id: 5,
      categoria:"placas-solares"
    },
    {
      nome: 'Painel Solar 550W Policristalino Half-Cell',
      imageUrl: 'placa2',
      preco: 580.0,
      parcelas: 'em até 10x de R$ 100,00',
      material: ['Silício Policristalino'],
      potencia: 550,
      marca: 'elgin',
      qntdVendas: 2,
      VerMais: {
        'descricao': 'Caixa de Conexão IP 68 com 3 diodos de by-pass',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Moldura': 'Alumínio Anodizado',
        'Coeficiente de Temperatura (Pmax)': '0.35 %/°C',
        'Coeficiente de Temperatura (Voc)': '0.27 %/°C',
        'Temperatura de Operação da Placa': '- 40 ~ + 85 °C',
        'Temperatura de Operação Ambiente': '45°C (± 2°C)',
        'Tipo de Vidro Frontal': '3.2mm temperado',
        'Nº de Células': '144 (6x24)',
        'Coeficiente de Temperatura (Isc)': '0.050 %/°C',
        'Dimensões (AxLxP)': '2279 X 1134 X 35mm',
        'Máxima carga estática na parte frontal (ex:carga sob placa)': '5400Pa',
        'Tipo de Material': 'Monocristalino (Half-cell)',
        'Tipo de Conector': 'Conectores MC4',
        'Eficiência do Módulo': '21.30%',
        'Nível de Eficiência Energética no Inmetro': 'Nível A',
        'Máxima carga estática traseira (ex:vento)': '2400Pa',
        'Área da seção do': 'cabo:4mm²',
        'REGISTRO INMETRO': '007202/2021',
        'Corrente Máxima por Fusíveis em Série': '25A',
        'Peso': '29kg',
        'CARACTERÍSTICAS': 'Economia Imediata Certificado pelo INMETRO Resistente'
      },
      id: 1,
      categoria:"placas-solares"
    },
    {
      nome: 'Kit Energia Solar 1,14kWp 570W',
      imageUrl: 'placaskit2un',
      preco: 1350.0,
      parcelas: 'em até 10x de R$ 135,00',
      material: ['Silício Monocristalino'],
      potencia: 570,
      marca: 'weg',
      qntdVendas: 3,
      VerMais: {
        'Descrição': 'Kit 3 Placa Solar Fotovoltaico 550W WEG',
        'Eficiência energética da placa solar': '21,48',
        'Largura x Comprimento': '227.8 cm x 113.4 cm',
        'Peso': '27,3 kg',
        'Tipo da placa solar': 'Monocristalino',
        'Com impacto positivo': 'Sim',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Sistemas': 'de 1500Vcc',
        'Tecnologia': 'MULTIBUSBAR',
        'Eficiência de': '21,3%',
        'Suporta': '5400Pa de carga no frontal e 2400Pa de carga no posterior',
        'Alta resistência ao' :'efeito PID, conforme IEC 62804',
        'Temperatura de operação de' :'-40° a 85°C',
        'Proteção anti-incêndio UL790' :'classe C',
        'Moldura de alumínio': 'anodizado'
      },
      id: 6,
      categoria:"placas-solares"
    },
    {
      nome: 'Painel Solar 590W Monocristalino Half-Cell',
      imageUrl: 'placa590',
      preco: 590.0,
      parcelas: 'em até 10x de R$ 70,50',
      material: ['Silício Monocristalino'],
      potencia: 555,
      marca: 'weg',
      qntdVendas: 3,
      VerMais: {
        'Descrição': 'Kit 3 Placa Solar Fotovoltaico 550W WEG',
        'Eficiência energética da placa solar': '21,48',
        'Largura x Comprimento': '227.8 cm x 113.4 cm',
        'Peso': '27,3 kg',
        'Tipo da placa solar': 'Monocristalino',
        'Com impacto positivo': 'Sim',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Sistemas': 'de 1500Vcc',
        'Tecnologia': 'MULTIBUSBAR',
        'Eficiência de': '21,3%',
        'Suporta': '5400Pa de carga no frontal e 2400Pa de carga no posterior',
        'Alta resistência ao' :'efeito PID, conforme IEC 62804',
        'Temperatura de operação de' :'-40° a 85°C',
        'Proteção anti-incêndio UL790' :'classe C',
        'Moldura de alumínio': 'anodizado'
      },
      id: 3,
      categoria:"placas-solares"
    },
    {
      nome: 'Placa Solar 630wp Modulo Monocristalino Weg',
      imageUrl: 'placa630',
      preco: 850.0,
      parcelas: 'em até 10x de R$ 85,00',
      material: ['Silício Monocristalino'],
      potencia: 630,
      marca: 'weg',
      qntdVendas: 3,
      VerMais: {
        'Descrição': 'Kit 3 Placa Solar Fotovoltaico 550W WEG',
        'Eficiência energética da placa solar': '21,48',
        'Largura x Comprimento': '227.8 cm x 113.4 cm',
        'Peso': '27,3 kg',
        'Tipo da placa solar': 'Monocristalino',
        'Com impacto positivo': 'Sim',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Sistemas': 'de 1500Vcc',
        'Tecnologia': 'MULTIBUSBAR',
        'Eficiência de': '21,3%',
        'Suporta': '5400Pa de carga no frontal e 2400Pa de carga no posterior',
        'Alta resistência ao' :'efeito PID, conforme IEC 62804',
        'Temperatura de operação de' :'-40° a 85°C',
        'Proteção anti-incêndio UL790' :'classe C',
        'Moldura de alumínio': 'anodizado'
      },
      id: 7,
      categoria:"placas-solares"
    },
    {
      nome: 'Placa Solar Fotovoltaico 630w Kit 4pçs Weg',
      imageUrl: 'placa630kit4un',
      preco: 3550.0,
      parcelas: 'em até 10x de R$ 355,00',
      material: ['Silício Monocristalino'],
      potencia: 630,
      marca: 'weg',
      qntdVendas: 3,
      VerMais: {
        'Descrição': 'Kit 3 Placa Solar Fotovoltaico 550W WEG',
        'Eficiência energética da placa solar': '21,48',
        'Largura x Comprimento': '227.8 cm x 113.4 cm',
        'Peso': '27,3 kg',
        'Tipo da placa solar': 'Monocristalino',
        'Com impacto positivo': 'Sim',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Sistemas': 'de 1500Vcc',
        'Tecnologia': 'MULTIBUSBAR',
        'Eficiência de': '21,3%',
        'Suporta': '5400Pa de carga no frontal e 2400Pa de carga no posterior',
        'Alta resistência ao' :'efeito PID, conforme IEC 62804',
        'Temperatura de operação de' :'-40° a 85°C',
        'Proteção anti-incêndio UL790' :'classe C',
        'Moldura de alumínio': 'anodizado'
      },
      id: 8,
      categoria:"placas-solares"
    },
    {
      nome: 'Placa Solar Fotovoltaico 555w Monocristalino',
      imageUrl: 'placa555',
      preco: 705.0,
      parcelas: 'em até 10x de R$ 70,50',
      material: ['Silício Monocristalino'],
      potencia: 555,
      marca: 'weg',
      qntdVendas: 3,
      VerMais: {
        'Descrição': 'Kit 3 Placa Solar Fotovoltaico 550W WEG',
        'Eficiência energética da placa solar': '21,48',
        'Largura x Comprimento': '227.8 cm x 113.4 cm',
        'Peso': '27,3 kg',
        'Tipo da placa solar': 'Monocristalino',
        'Com impacto positivo': 'Sim',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Sistemas': 'de 1500Vcc',
        'Tecnologia': 'MULTIBUSBAR',
        'Eficiência de': '21,3%',
        'Suporta': '5400Pa de carga no frontal e 2400Pa de carga no posterior',
        'Alta resistência ao' :'efeito PID, conforme IEC 62804',
        'Temperatura de operação de' :'-40° a 85°C',
        'Proteção anti-incêndio UL790' :'classe C',
        'Moldura de alumínio': 'anodizado'
      },
      id: 9,
      categoria:"placas-solares"
    },
    {
      nome: 'Painel Solar 590W Monocristalino Half-Cell',
      imageUrl: 'placa590',
      preco: 590.0,
      parcelas: 'em até 10x de R$ 70,50',
      material: ['Silício Monocristalino'],
      potencia: 555,
      marca: 'weg',
      qntdVendas: 3,
      VerMais: {
        'Descrição': 'Kit 3 Placa Solar Fotovoltaico 550W WEG',
        'Eficiência energética da placa solar': '21,48',
        'Largura x Comprimento': '227.8 cm x 113.4 cm',
        'Peso': '27,3 kg',
        'Tipo da placa solar': 'Monocristalino',
        'Com impacto positivo': 'Sim',
        'Máximo Tensão de Trabalho': '1500Vcc',
        'Sistemas': 'de 1500Vcc',
        'Tecnologia': 'MULTIBUSBAR',
        'Eficiência de': '21,3%',
        'Suporta': '5400Pa de carga no frontal e 2400Pa de carga no posterior',
        'Alta resistência ao' :'efeito PID, conforme IEC 62804',
        'Temperatura de operação de' :'-40° a 85°C',
        'Proteção anti-incêndio UL790' :'classe C',
        'Moldura de alumínio': 'anodizado'
      },
      id:10 ,
      categoria:"placas-solares"
    },
  ]

  function getProduct(id){
    return this.produtos.find(objeto => objeto.id === id)
  }
  return { produtos, getProduct }
})
